CREATE TABLE IF NOT EXISTS posts (
    shortcode TEXT PRIMARY KEY,
    video_url TEXT,
    video_view_count INTEGER,
    caption TEXT NOT NULL,
    caption_hashtags TEXT NOT NULL,
    caption_mentions TEXT NOT NULL,
    comments INTEGER NOT NULL,
    `date` INTEGER NOT NULL,
    date_local INTEGER NOT NULL,
    date_utc INTEGER NOT NULL,
    is_pinned INTEGER NOT NULL,
    is_video INTEGER NOT NULL,
    likes INTEGER NOT NULL,
    location TEXT,
    mediacount INTEGER NOT NULL,
    mediaid INTEGER NOT NULL,
    owner_id TEXT NOT NULL,
    owner_profile TEXT NOT NULL,
    owner_username TEXT NOT NULL,
    pcaption TEXT NOT NULL,
    profile TEXT NOT NULL,
    tagged_users TEXT NOT NULL,
    typename TEXT NOT NULL,
    url TEXT NOT NULL,
    viewer_has_liked TEXT
) STRICT;
